export const SliderData = [
    {
      image:
        'https://iili.io/HqqvLQ4.png'
    },
    {
      image:
        'https://iili.io/HqqviTG.png'
    },
    {
      image:
        'https://iili.io/Hqqvsjf.png'
    },
    {
      image:
        'https://iili.io/HqqvD4S.png'
    },
    {
      image:
        'https://iili.io/Hqqvm37.png'
    },
    {
      image:
        'https://iili.io/HqqhbOQ.png'
    },
    {
      image:
        'https://iili.io/Hqq8Ca1.png'
    },
    {
      image:
        'https://iili.io/Hqq8oyg.png'
    },
    {
      image:
        'https://iili.io/Hqq8f6B.png'
    },
    {
      image:
        'https://iili.io/Hqq8KGV.png'
    },
    {
      image:
        'https://iili.io/Hqq8FCQ.png'
    },
    {
      image:
        'https://iili.io/Hqq82Zx.png'
    }
  ];